<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Roles
        $super_admin_role = Role::create(['name' => 'super_admin', 'guard_name' => 'web', 'display_name' => 'Super Admin']);
        $admin_role = Role::create(['name' => 'admin', 'guard_name' => 'web', 'display_name' => 'Admin']);
        $employee_role = Role::create(['name' => 'employee', 'guard_name' => 'web', 'display_name' => 'Employee']);

        //Permissions
        $permissions = [
            ['name' => 'company.index', 'display_name' => 'Company Index', 'guard_name' => 'web'],
            ['name' => 'company.show', 'display_name' => 'Company Show', 'guard_name' => 'web'],
            ['name' => 'company.create', 'display_name' => 'Company Create', 'guard_name' => 'web'],
            ['name' => 'company.edit', 'display_name' => 'Company Edit', 'guard_name' => 'web'],
            ['name' => 'company.destroy', 'display_name' => 'Company Destroy', 'guard_name' => 'web'],
            ['name' => 'company_branch.index', 'display_name' => 'Company Branch Index', 'guard_name' => 'web'],
            ['name' => 'company_branch.show', 'display_name' => 'Company Branch Show', 'guard_name' => 'web'],
            ['name' => 'company_branch.create', 'display_name' => 'Company Branch Create', 'guard_name' => 'web'],
            ['name' => 'company_branch.edit', 'display_name' => 'Company Branch Edit', 'guard_name' => 'web'],
            ['name' => 'company_branch.destroy', 'display_name' => 'Company Branch Destroy', 'guard_name' => 'web'],
            ['name' => 'designation.index', 'display_name' => 'Designation Index', 'guard_name' => 'web'],
            ['name' => 'designation.show', 'display_name' => 'Designation Show', 'guard_name' => 'web'],
            ['name' => 'designation.create', 'display_name' => 'Designation Create', 'guard_name' => 'web'],
            ['name' => 'designation.edit', 'display_name' => 'Designation Edit', 'guard_name' => 'web'],
            ['name' => 'designation.destroy', 'display_name' => 'Designation Destroy', 'guard_name' => 'web'],
            ['name' => 'department.index', 'display_name' => 'Department Index', 'guard_name' => 'web'],
            ['name' => 'department.show', 'display_name' => 'Department Show', 'guard_name' => 'web'],
            ['name' => 'department.create', 'display_name' => 'Department Create', 'guard_name' => 'web'],
            ['name' => 'department.edit', 'display_name' => 'Department Edit', 'guard_name' => 'web'],
            ['name' => 'department.destroy', 'display_name' => 'Department Destroy', 'guard_name' => 'web'],
            ['name' => 'employee.index', 'display_name' => 'Employee Index', 'guard_name' => 'web'],
            ['name' => 'employee.show', 'display_name' => 'Employee Show', 'guard_name' => 'web'],
            ['name' => 'employee.create', 'display_name' => 'Employee Create', 'guard_name' => 'web'],
            ['name' => 'employee.edit', 'display_name' => 'Employee Edit', 'guard_name' => 'web'],
            ['name' => 'employee.destroy', 'display_name' => 'Employee Destroy', 'guard_name' => 'web'],
            ['name' => 'attendance.index', 'display_name' => 'Attendance Index', 'guard_name' => 'web'],
            ['name' => 'attendance.show', 'display_name' => 'Attendance Show', 'guard_name' => 'web'],
            ['name' => 'attendance.create', 'display_name' => 'Attendance Create', 'guard_name' => 'web'],
            ['name' => 'attendance.edit', 'display_name' => 'Attendance Edit', 'guard_name' => 'web'],
            ['name' => 'attendance.destroy', 'display_name' => 'Attendance Destroy', 'guard_name' => 'web'],
            ['name' => 'leave.index', 'display_name' => 'Leave Index', 'guard_name' => 'web'],
            ['name' => 'leave.show', 'display_name' => 'Leave Show', 'guard_name' => 'web'],
            ['name' => 'leave.create', 'display_name' => 'Leave Create', 'guard_name' => 'web'],
            ['name' => 'leave.edit', 'display_name' => 'Leave Edit', 'guard_name' => 'web'],
            ['name' => 'leave.destroy', 'display_name' => 'Leave Destroy', 'guard_name' => 'web'],
            ['name' => 'leave.approval', 'display_name' => 'Leave Approval', 'guard_name' => 'web'],
            ['name' => 'salary.index', 'display_name' => 'Salary Index', 'guard_name' => 'web'],
            ['name' => 'salary.show', 'display_name' => 'Salary Show', 'guard_name' => 'web'],
            ['name' => 'salary.create', 'display_name' => 'Salary Create', 'guard_name' => 'web'],
            ['name' => 'salary.edit', 'display_name' => 'Salary Edit', 'guard_name' => 'web'],
            ['name' => 'salary.destroy', 'display_name' => 'Salary Destroy', 'guard_name' => 'web'],
            ['name' => 'bank.index', 'display_name' => 'Bank Index', 'guard_name' => 'web'],
            ['name' => 'bank.show', 'display_name' => 'Bank Show', 'guard_name' => 'web'],
            ['name' => 'bank.create', 'display_name' => 'Bank Create', 'guard_name' => 'web'],
            ['name' => 'bank.edit', 'display_name' => 'Bank Edit', 'guard_name' => 'web'],
            ['name' => 'bank.destroy', 'display_name' => 'Bank Destroy', 'guard_name' => 'web'],
            ['name' => 'leave_type.index', 'display_name' => 'Leave Type Index', 'guard_name' => 'web'],
            ['name' => 'leave_type.show', 'display_name' => 'Leave Type Show', 'guard_name' => 'web'],
            ['name' => 'leave_type.create', 'display_name' => 'Leave Type Create', 'guard_name' => 'web'],
            ['name' => 'leave_type.edit', 'display_name' => 'Leave Type Edit', 'guard_name' => 'web'],
            ['name' => 'leave_type.destroy', 'display_name' => 'Leave Type Destroy', 'guard_name' => 'web'],
            ['name' => 'salary_type.index', 'display_name' => 'Salary Type Index', 'guard_name' => 'web'],
            ['name' => 'salary_type.show', 'display_name' => 'Salary Type Show', 'guard_name' => 'web'],
            ['name' => 'salary_type.create', 'display_name' => 'Salary Type Create', 'guard_name' => 'web'],
            ['name' => 'salary_type.edit', 'display_name' => 'Salary Type Edit', 'guard_name' => 'web'],
            ['name' => 'salary_type.destroy', 'display_name' => 'Salary Type Destroy', 'guard_name' => 'web'],
            ['name' => 'salary_item.index', 'display_name' => 'Salary Item Index', 'guard_name' => 'web'],
            ['name' => 'salary_item.show', 'display_name' => 'Salary Item Show', 'guard_name' => 'web'],
            ['name' => 'salary_item.create', 'display_name' => 'Salary Item Create', 'guard_name' => 'web'],
            ['name' => 'salary_item.edit', 'display_name' => 'Salary Item Edit', 'guard_name' => 'web'],
            ['name' => 'salary_item.destroy', 'display_name' => 'Salary Item Destroy', 'guard_name' => 'web'],
            ['name' => 'salary_process.index', 'display_name' => 'Salary Process Index', 'guard_name' => 'web'],
            ['name' => 'salary_process.show', 'display_name' => 'Salary Process Show', 'guard_name' => 'web'],
            ['name' => 'salary_process.create', 'display_name' => 'Salary Process Create', 'guard_name' => 'web'],
            ['name' => 'salary_process.edit', 'display_name' => 'Salary Process Edit', 'guard_name' => 'web'],
            ['name' => 'salary_process.destroy', 'display_name' => 'Salary Process Destroy', 'guard_name' => 'web'],
            ['name' => 'salary_view.index', 'display_name' => 'Salary View Index', 'guard_name' => 'web'],
            ['name' => 'salary_view.show', 'display_name' => 'Salary View Show', 'guard_name' => 'web'],
            ['name' => 'claim.index', 'display_name' => 'Claim Index', 'guard_name' => 'web'],
            ['name' => 'claim.show', 'display_name' => 'Claim Show', 'guard_name' => 'web'],
            ['name' => 'claim.create', 'display_name' => 'Claim Create', 'guard_name' => 'web'],
            ['name' => 'claim.edit', 'display_name' => 'Claim Edit', 'guard_name' => 'web'],
            ['name' => 'claim.destroy', 'display_name' => 'Claim Destroy', 'guard_name' => 'web'],
            ['name' => 'claim_approval.index', 'display_name' => 'Claim Approval Index', 'guard_name' => 'web'],
            ['name' => 'claim_approval.show', 'display_name' => 'Claim Approval Show', 'guard_name' => 'web'],
            ['name' => 'claim_approval.approval', 'display_name' => 'Claim Approval Action', 'guard_name' => 'web'],
            ['name' => 'entity.index', 'display_name' => 'Business Partner Index', 'guard_name' => 'web'],
            ['name' => 'entity.show', 'display_name' => 'Business Partner Show', 'guard_name' => 'web'],
            ['name' => 'entity.create', 'display_name' => 'Business Partner Create', 'guard_name' => 'web'],
            ['name' => 'entity.edit', 'display_name' => 'Business Partner Edit', 'guard_name' => 'web'],
            ['name' => 'entity.destroy', 'display_name' => 'Business Partner Destroy', 'guard_name' => 'web'],
            ['name' => 'entity_address.index', 'display_name' => 'Business Partner Address Index', 'guard_name' => 'web'],
            ['name' => 'entity_address.show', 'display_name' => 'Business Partner Address Show', 'guard_name' => 'web'],
            ['name' => 'entity_address.create', 'display_name' => 'Business Partner Address Create', 'guard_name' => 'web'],
            ['name' => 'entity_address.edit', 'display_name' => 'Business Partner Address Edit', 'guard_name' => 'web'],
            ['name' => 'entity_address.destroy', 'display_name' => 'Business Partner Address Destroy', 'guard_name' => 'web'],
            ['name' => 'entity_contact.index', 'display_name' => 'Business Partner Contact Index', 'guard_name' => 'web'],
            ['name' => 'entity_contact.show', 'display_name' => 'Business Partner Contact Show', 'guard_name' => 'web'],
            ['name' => 'entity_contact.create', 'display_name' => 'Business Partner Contact Create', 'guard_name' => 'web'],
            ['name' => 'entity_contact.edit', 'display_name' => 'Business Partner Contact Edit', 'guard_name' => 'web'],
            ['name' => 'entity_contact.destroy', 'display_name' => 'Business Partner Contact Destroy', 'guard_name' => 'web'],
            ['name' => 'product.index', 'display_name' => 'Product Index', 'guard_name' => 'web'],
            ['name' => 'product.show', 'display_name' => 'Product Show', 'guard_name' => 'web'],
            ['name' => 'product.create', 'display_name' => 'Product Create', 'guard_name' => 'web'],
            ['name' => 'product.edit', 'display_name' => 'Product Edit', 'guard_name' => 'web'],
            ['name' => 'product.destroy', 'display_name' => 'Product Destroy', 'guard_name' => 'web'],
            ['name' => 'product_category.index', 'display_name' => 'Product Category Index', 'guard_name' => 'web'],
            ['name' => 'product_category.show', 'display_name' => 'Product Category Show', 'guard_name' => 'web'],
            ['name' => 'product_category.create', 'display_name' => 'Product Category Create', 'guard_name' => 'web'],
            ['name' => 'product_category.edit', 'display_name' => 'Product Category Edit', 'guard_name' => 'web'],
            ['name' => 'product_category.destroy', 'display_name' => 'Product Category Destroy', 'guard_name' => 'web'],
            ['name' => 'customer_reference.index', 'display_name' => 'Customer Reference Index', 'guard_name' => 'web'],
            ['name' => 'customer_reference.show', 'display_name' => 'Customer Reference Show', 'guard_name' => 'web'],
            ['name' => 'customer_reference.create', 'display_name' => 'Customer Reference Create', 'guard_name' => 'web'],
            ['name' => 'customer_reference.edit', 'display_name' => 'Customer Reference Edit', 'guard_name' => 'web'],
            ['name' => 'customer_reference.destroy', 'display_name' => 'Customer Reference Destroy', 'guard_name' => 'web'],
            ['name' => 'quotation.index', 'display_name' => 'Quotation Index', 'guard_name' => 'web'],
            ['name' => 'quotation.show', 'display_name' => 'Quotation Show', 'guard_name' => 'web'],
            ['name' => 'quotation.create', 'display_name' => 'Quotation Create', 'guard_name' => 'web'],
            ['name' => 'quotation.edit', 'display_name' => 'Quotation Edit', 'guard_name' => 'web'],
            ['name' => 'quotation.destroy', 'display_name' => 'Quotation Destroy', 'guard_name' => 'web'],
            ['name' => 'quotation_item.index', 'display_name' => 'Quotation Item Index', 'guard_name' => 'web'],
            ['name' => 'quotation_item.show', 'display_name' => 'Quotation Item Show', 'guard_name' => 'web'],
            ['name' => 'quotation_item.create', 'display_name' => 'Quotation Item Create', 'guard_name' => 'web'],
            ['name' => 'quotation_item.edit', 'display_name' => 'Quotation Item Edit', 'guard_name' => 'web'],
            ['name' => 'quotation_item.destroy', 'display_name' => 'Quotation Item Destroy', 'guard_name' => 'web'],
            ['name' => 'invoice.index', 'display_name' => 'Invoice Index', 'guard_name' => 'web'],
            ['name' => 'invoice.show', 'display_name' => 'Invoice Show', 'guard_name' => 'web'],
            ['name' => 'invoice.create', 'display_name' => 'Invoice Create', 'guard_name' => 'web'],
            ['name' => 'invoice.edit', 'display_name' => 'Invoice Edit', 'guard_name' => 'web'],
            ['name' => 'invoice.destroy', 'display_name' => 'Invoice Destroy', 'guard_name' => 'web'],
            ['name' => 'invoice_item.index', 'display_name' => 'Invoice Item Index', 'guard_name' => 'web'],
            ['name' => 'invoice_item.show', 'display_name' => 'Invoice Item Show', 'guard_name' => 'web'],
            ['name' => 'invoice_item.create', 'display_name' => 'Invoice Item Create', 'guard_name' => 'web'],
            ['name' => 'invoice_item.edit', 'display_name' => 'Invoice Item Edit', 'guard_name' => 'web'],
            ['name' => 'invoice_item.destroy', 'display_name' => 'Invoice Item Destroy', 'guard_name' => 'web'],
            ['name' => 'company_bank.index', 'display_name' => 'Company Bank Index', 'guard_name' => 'web'],
            ['name' => 'company_bank.show', 'display_name' => 'Company Bank Show', 'guard_name' => 'web'],
            ['name' => 'company_bank.create', 'display_name' => 'Company Bank Create', 'guard_name' => 'web'],
            ['name' => 'company_bank.edit', 'display_name' => 'Company Bank Edit', 'guard_name' => 'web'],
            ['name' => 'company_bank.destroy', 'display_name' => 'Company Bank Destroy', 'guard_name' => 'web'],
            ['name' => 'transaction.index', 'display_name' => 'Transaction Index', 'guard_name' => 'web'],
            ['name' => 'transaction.show', 'display_name' => 'Transaction Show', 'guard_name' => 'web'],
            ['name' => 'transaction.create', 'display_name' => 'Transaction Create', 'guard_name' => 'web'],
            ['name' => 'transaction.edit', 'display_name' => 'Transaction Edit', 'guard_name' => 'web'],
            ['name' => 'transaction.destroy', 'display_name' => 'Transaction Destroy', 'guard_name' => 'web'],
            ['name' => 'project.index', 'display_name' => 'Project Index', 'guard_name' => 'web'],
            ['name' => 'project.show', 'display_name' => 'Project Show', 'guard_name' => 'web'],
            ['name' => 'project.create', 'display_name' => 'Project Create', 'guard_name' => 'web'],
            ['name' => 'project.edit', 'display_name' => 'Project Edit', 'guard_name' => 'web'],
            ['name' => 'project.destroy', 'display_name' => 'Project Destroy', 'guard_name' => 'web'],

        ];

        Permission::insert($permissions);

        // Grant all permissions to super_admin
        $all_permissions = Permission::all();
        $super_admin_role->syncPermissions($all_permissions);

        // Grant permissions to admin
        $admin_permissions = Permission::whereNotIn('id', [1, 2, 3, 4, 5])->get();
        $admin_role->syncPermissions($admin_permissions);

        // Grant permissions to employee
        $employee_permissions = Permission::whereIn('name', [
            'company.show',
            'company_branch.show',
            'employee.show',
            'salary_view.index',
            'salary_view.show',
            'leave.index',
            'leave.show',
            'leave.create',
            'leave.edit',
            'leave.destroy',
            'claim.index',
            'claim.show',
            'claim.create',
            'claim.edit',
            'claim.destroy',
            'entity.index',
            'entity.show',
            'entity.create',
            'entity.edit',
            'entity.destroy',
            'entity_address.index',
            'entity_address.show',
            'entity_address.create',
            'entity_address.edit',
            'entity_address.destroy',
            'entity_contact.index',
            'entity_contact.show',
            'entity_contact.create',
            'entity_contact.edit',
            'entity_contact.destroy',
            'product.index',
            'product.show',
            'product_category.index',
            'product_category.show',
            'attendance.index',
            'attendance.show',
            'attendance.create',
            'attendance.edit',
            'attendance.destroy',
            'quotation.index',
            'quotation.show',
            'quotation.create',
            'quotation.edit',
            'quotation.destroy',
            'quotation_item.index',
            'quotation_item.show',
            'quotation_item.create',
            'quotation_item.edit',
            'quotation_item.destroy',
            'invoice.index',
            'invoice.show',
            'invoice.create',
            'invoice.edit',
            'invoice.destroy',
            'invoice_item.index',
            'invoice_item.show',
            'invoice_item.create',
            'invoice_item.edit',
            'invoice_item.destroy',
            'project.index',
            'project.show',
            'project.create',
            'project.edit',
            'project.destroy',
        ])->get();
        $employee_role->syncPermissions($employee_permissions);
    }
}
