<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Roles
        $super_admin_role = Role::create(['name' => 'super_admin', 'guard_name' => 'web', 'display_name' => 'Super Admin']);
        $admin_role = Role::create(['name' => 'admin', 'guard_name' => 'web', 'display_name' => 'Admin']);
        $employee_role = Role::create(['name' => 'employee', 'guard_name' => 'web', 'display_name' => 'Employee']);

        //Permissions
        $permissions = [
            [
                'name' => 'company.index',
                'display_name' => 'Showing Company List',
                'description' => 'This permission allows a user to view the list of companies',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company.show',
                'display_name' => 'Showing Company Detail',
                'description' => 'This permission allows a user to view the details of a specific company',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company.create',
                'display_name' => 'Creating Company',
                'description' => 'This permission allows a user to create a new company',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company.edit',
                'display_name' => 'Editing Company',
                'description' => 'This permission allows a user to edit an existing company',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company.destroy',
                'display_name' => 'Deleting Company',
                'description' => 'This permission allows a user to delete a company',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_branch.index',
                'display_name' => 'Showing Company Branch List',
                'description' => 'This permission allows a user to view the list of company branches',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_branch.show',
                'display_name' => 'Showing Company Branch Detail',
                'description' => 'This permission allows a user to view the details of a specific company branch',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_branch.create',
                'display_name' => 'Creating Company Branch',
                'description' => 'This permission allows a user to create a new company branch',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_branch.edit',
                'display_name' => 'Editing Company Branch',
                'description' => 'This permission allows a user to edit an existing company branch',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_branch.destroy',
                'display_name' => 'Deleting Company Branch',
                'description' => 'This permission allows a user to delete a company branch',
                'guard_name' => 'web',
            ],
            [
                'name' => 'designation.index',
                'display_name' => 'Showing Designation List',
                'description' => 'This permission allows a user to view the list of designations',
                'guard_name' => 'web',
            ],
            [
                'name' => 'designation.show',
                'display_name' => 'Showing Designation Detail',
                'description' => 'This permission allows a user to view the details of a specific designation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'designation.create',
                'display_name' => 'Creating Designation',
                'description' => 'This permission allows a user to create a new designation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'designation.edit',
                'display_name' => 'Editing Designation',
                'description' => 'This permission allows a user to edit an existing designation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'designation.destroy',
                'display_name' => 'Deleting Designation',
                'description' => 'This permission allows a user to delete a designation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'department.index',
                'display_name' => 'Showing Department List',
                'description' => 'This permission allows a user to view the list of departments',
                'guard_name' => 'web',
            ],
            [
                'name' => 'department.show',
                'display_name' => 'Showing Department Detail',
                'description' => 'This permission allows a user to view the details of a specific department',
                'guard_name' => 'web',
            ],
            [
                'name' => 'department.create',
                'display_name' => 'Creating Department',
                'description' => 'This permission allows a user to create a new department',
                'guard_name' => 'web',
            ],
            [
                'name' => 'department.edit',
                'display_name' => 'Editing Department',
                'description' => 'This permission allows a user to edit an existing department',
                'guard_name' => 'web',
            ],
            [
                'name' => 'department.destroy',
                'display_name' => 'Deleting Department',
                'description' => 'This permission allows a user to delete a department',
                'guard_name' => 'web',
            ],
            [
                'name' => 'employee.index',
                'display_name' => 'Showing Employee List',
                'description' => 'This permission allows a user to view the list of employees',
                'guard_name' => 'web',
            ],
            [
                'name' => 'employee.show',
                'display_name' => 'Showing Employee Detail',
                'description' => 'This permission allows a user to view the details of a specific employee',
                'guard_name' => 'web',
            ],
            [
                'name' => 'employee.create',
                'display_name' => 'Creating Employee',
                'description' => 'This permission allows a user to create a new employee',
                'guard_name' => 'web',
            ],
            [
                'name' => 'employee.edit',
                'display_name' => 'Editing Employee',
                'description' => 'This permission allows a user to edit an existing employee',
                'guard_name' => 'web',
            ],
            [
                'name' => 'employee.destroy',
                'display_name' => 'Deleting Employee',
                'description' => 'This permission allows a user to delete an employee',
                'guard_name' => 'web',
            ],
            [
                'name' => 'attendance.index',
                'display_name' => 'Showing Attendance List',
                'description' => 'This permission allows a user to view the list of attendances',
                'guard_name' => 'web',
            ],
            [
                'name' => 'attendance.show',
                'display_name' => 'Showing Attendance Detail',
                'description' => 'This permission allows a user to view the details of a specific attendance',
                'guard_name' => 'web',
            ],
            [
                'name' => 'attendance.create',
                'display_name' => 'Creating Attendance',
                'description' => 'This permission allows a user to create a new attendance',
                'guard_name' => 'web',
            ],
            [
                'name' => 'attendance.edit',
                'display_name' => 'Editing Attendance',
                'description' => 'This permission allows a user to edit an existing attendance',
                'guard_name' => 'web',
            ],
            [
                'name' => 'attendance.destroy',
                'display_name' => 'Deleting Attendance',
                'description' => 'This permission allows a user to delete an attendance',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.index',
                'display_name' => 'Showing Leave Request List',
                'description' => 'This permission allows a user to view the list of leave requests',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.show',
                'display_name' => 'Showing Leave Request Detail',
                'description' => 'This permission allows a user to view the details of a specific leave request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.create',
                'display_name' => 'Creating Leave Request',
                'description' => 'This permission allows a user to create a new leave request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.edit',
                'display_name' => 'Editing Leave Request',
                'description' => 'This permission allows a user to edit an existing leave request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.destroy',
                'display_name' => 'Deleting Leave Request',
                'description' => 'This permission allows a user to delete a leave request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave.approval',
                'display_name' => 'Approving Leave Request',
                'description' => 'This permission allows a user to make approval on a leave request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary.index',
                'display_name' => 'Showing Salary List',
                'description' => 'This permission allows a user to view the list of salaries',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary.show',
                'display_name' => 'Showing Salary Detail',
                'description' => 'This permission allows a user to view the details of a specific salary',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary.create',
                'display_name' => 'Creating Salary',
                'description' => 'This permission allows a user to create a new salary',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary.edit',
                'display_name' => 'Editing Salary',
                'description' => 'This permission allows a user to edit an existing salary',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary.destroy',
                'display_name' => 'Deleting Salary',
                'description' => 'This permission allows a user to delete a salary',
                'guard_name' => 'web',
            ],
            [
                'name' => 'bank.index',
                'display_name' => 'Showing Bank List',
                'description' => 'This permission allows a user to view the list of bank accounts',
                'guard_name' => 'web',
            ],
            [
                'name' => 'bank.show',
                'display_name' => 'Showing Bank Detail',
                'description' => 'This permission allows a user to view the details of a specific bank account',
                'guard_name' => 'web',
            ],
            [
                'name' => 'bank.create',
                'display_name' => 'Creating Bank',
                'description' => 'This permission allows a user to create a new bank account',
                'guard_name' => 'web',
            ],
            [
                'name' => 'bank.edit',
                'display_name' => 'Editing Bank',
                'description' => 'This permission allows a user to edit an existing bank account',
                'guard_name' => 'web',
            ],
            [
                'name' => 'bank.destroy',
                'display_name' => 'Deleting Bank',
                'description' => 'This permission allows a user to delete a bank account',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave_type.index',
                'display_name' => 'Showing Leave Type List',
                'description' => 'This permission allows a user to view the list of leave types',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave_type.show',
                'display_name' => 'Showing Leave Type Detail',
                'description' => 'This permission allows a user to view the details of a specific leave type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave_type.create',
                'display_name' => 'Creating Leave Type',
                'description' => 'This permission allows a user to create a new leave type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave_type.edit',
                'display_name' => 'Editing Leave Type',
                'description' => 'This permission allows a user to edit an existing leave type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'leave_type.destroy',
                'display_name' => 'Deleting Leave Type',
                'description' => 'This permission allows a user to delete a leave type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_type.index',
                'display_name' => 'Showing Salary Type List',
                'description' => 'This permission allows a user to view the list of salary types',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_type.show',
                'display_name' => 'Showing Salary Type Detail',
                'description' => 'This permission allows a user to view the details of a specific salary type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_type.create',
                'display_name' => 'Creating Salary Type',
                'description' => 'This permission allows a user to create a new salary type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_type.edit',
                'display_name' => 'Editing Salary Type',
                'description' => 'This permission allows a user to edit an existing salary type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_type.destroy',
                'display_name' => 'Deleting Salary Type',
                'description' => 'This permission allows a user to delete a salary type',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_item.index',
                'display_name' => 'Showing Salary Item List',
                'description' => 'This permission allows a user to view the list of salary items',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_item.show',
                'display_name' => 'Showing Salary Item Detail',
                'description' => 'This permission allows a user to view the details of a specific salary item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_item.create',
                'display_name' => 'Creating Salary Item',
                'description' => 'This permission allows a user to create a new salary item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_item.edit',
                'display_name' => 'Editing Salary Item',
                'description' => 'This permission allows a user to edit an existing salary item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_item.destroy',
                'display_name' => 'Deleting Salary Item',
                'description' => 'This permission allows a user to delete a salary item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_process.index',
                'display_name' => 'Showing Salary Process List',
                'description' => 'This permission allows a user to view the list of salary processes',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_process.show',
                'display_name' => 'Showing Salary Process Detail',
                'description' => 'This permission allows a user to view the details of a specific salary process',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_process.create',
                'display_name' => 'Creating Salary Process',
                'description' => 'This permission allows a user to create a new salary process',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_process.edit',
                'display_name' => 'Editing Salary Process',
                'description' => 'This permission allows a user to edit an existing salary process',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_process.destroy',
                'display_name' => 'Deleting Salary Process',
                'description' => 'This permission allows a user to delete a salary process',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_view.index',
                'display_name' => 'Showing Payroll List',
                'description' => 'This permission allows a user to view the list of payrolls',
                'guard_name' => 'web',
            ],
            [
                'name' => 'salary_view.show',
                'display_name' => 'Showing Payroll Detail',
                'description' => 'This permission allows a user to view the details of a specific payroll',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim.index',
                'display_name' => 'Showing Claim Request List',
                'description' => 'This permission allows a user to view the list of claim requests',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim.show',
                'display_name' => 'Showing Claim Request Detail',
                'description' => 'This permission allows a user to view the details of a specific claim request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim.create',
                'display_name' => 'Creating Claim Request',
                'description' => 'This permission allows a user to create a new claim request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim.edit',
                'display_name' => 'Editing Claim Request',
                'description' => 'This permission allows a user to edit an existing claim request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim.destroy',
                'display_name' => 'Deleting Claim Request',
                'description' => 'This permission allows a user to delete a claim request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim_approval.index',
                'display_name' => 'Showing Claim Approval List',
                'description' => 'This permission allows a user to view the list of claim approvals',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim_approval.show',
                'display_name' => 'Showing Claim Approval Detail',
                'description' => 'This permission allows a user to view the details of a specific claim approval',
                'guard_name' => 'web',
            ],
            [
                'name' => 'claim_approval.approval',
                'display_name' => 'Claim Approval Action',
                'description' => 'This permission allows a user to approve or reject a claim request',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity.index',
                'display_name' => 'Showing Business Partner List',
                'description' => 'This permission allows a user to view the list of business partners',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity.show',
                'display_name' => 'Showing Business Partner Detail',
                'description' => 'This permission allows a user to view the details of a specific business partner',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity.create',
                'display_name' => 'Creating Business Partner',
                'description' => 'This permission allows a user to create a new business partner',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity.edit',
                'display_name' => 'Editing Business Partner',
                'description' => 'This permission allows a user to edit an existing business partner',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity.destroy',
                'display_name' => 'Deleting Business Partner',
                'description' => 'This permission allows a user to delete a business partner',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_address.index',
                'display_name' => 'Showing Business Partner Address List',
                'description' => 'This permission allows a user to view the list of business partner addresses',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_address.show',
                'display_name' => 'Showing Business Partner Address Detail',
                'description' => 'This permission allows a user to view the details of a specific business partner address',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_address.create',
                'display_name' => 'Creating Business Partner Address',
                'description' => 'This permission allows a user to create a new business partner address',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_address.edit',
                'display_name' => 'Editing Business Partner Address',
                'description' => 'This permission allows a user to edit an existing business partner address',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_address.destroy',
                'display_name' => 'Deleting Business Partner Address',
                'description' => 'This permission allows a user to delete a business partner address',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_contact.index',
                'display_name' => 'Showing Business Partner Contact List',
                'description' => 'This permission allows a user to view the list of business partner contacts',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_contact.show',
                'display_name' => 'Showing Business Partner Contact Detail',
                'description' => 'This permission allows a user to view the details of a specific business partner contact',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_contact.create',
                'display_name' => 'Creating Business Partner Contact',
                'description' => 'This permission allows a user to create a new business partner contact',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_contact.edit',
                'display_name' => 'Editing Business Partner Contact',
                'description' => 'This permission allows a user to edit an existing business partner contact',
                'guard_name' => 'web',
            ],
            [
                'name' => 'entity_contact.destroy',
                'display_name' => 'Deleting Business Partner Contact',
                'description' => 'This permission allows a user to delete a business partner contact',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product.index',
                'display_name' => 'Showing Product List',
                'description' => 'This permission allows a user to view the list of products',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product.show',
                'display_name' => 'Showing Product Detail',
                'description' => 'This permission allows a user to view the details of a specific product',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product.create',
                'display_name' => 'Creating Product',
                'description' => 'This permission allows a user to create a new product',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product.edit',
                'display_name' => 'Editing Product',
                'description' => 'This permission allows a user to edit an existing product',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product.destroy',
                'display_name' => 'Deleting Product',
                'description' => 'This permission allows a user to delete a product',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product_category.index',
                'display_name' => 'Showing Product Category List',
                'description' => 'This permission allows a user to view the list of product categories',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product_category.show',
                'display_name' => 'Showing Product Category Detail',
                'description' => 'This permission allows a user to view the details of a specific product category',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product_category.create',
                'display_name' => 'Creating Product Category',
                'description' => 'This permission allows a user to create a new product category',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product_category.edit',
                'display_name' => 'Editing Product Category',
                'description' => 'This permission allows a user to edit an existing product category',
                'guard_name' => 'web',
            ],
            [
                'name' => 'product_category.destroy',
                'display_name' => 'Deleting Product Category',
                'description' => 'This permission allows a user to delete a product category',
                'guard_name' => 'web',
            ],
            [
                'name' => 'customer_reference.index',
                'display_name' => 'Showing Quotation Customer List',
                'description' => 'This permission allows a user to view the list of quotation customers',
                'guard_name' => 'web',
            ],
            [
                'name' => 'customer_reference.show',
                'display_name' => 'Showing Quotation Customer Detail',
                'description' => 'This permission allows a user to view the details of a specific quotation customer',
                'guard_name' => 'web',
            ],
            [
                'name' => 'customer_reference.create',
                'display_name' => 'Creating Quotation Customer',
                'description' => 'This permission allows a user to create a new quotation customer',
                'guard_name' => 'web',
            ],
            [
                'name' => 'customer_reference.edit',
                'display_name' => 'Editing Quotation Customer',
                'description' => 'This permission allows a user to edit an existing quotation customer',
                'guard_name' => 'web',
            ],
            [
                'name' => 'customer_reference.destroy',
                'display_name' => 'Deleting Quotation Customer',
                'description' => 'This permission allows a user to delete a quotation customer',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation.index',
                'display_name' => 'Showing Quotation List',
                'description' => 'This permission allows a user to view the list of quotations',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation.show',
                'display_name' => 'Showing Quotation Detail',
                'description' => 'This permission allows a user to view the details of a specific quotation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation.create',
                'display_name' => 'Creating Quotation',
                'description' => 'This permission allows a user to create a new quotation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation.edit',
                'display_name' => 'Editing Quotation',
                'description' => 'This permission allows a user to edit an existing quotation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation.destroy',
                'display_name' => 'Deleting Quotation',
                'description' => 'This permission allows a user to delete a quotation',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation_item.index',
                'display_name' => 'Showing Quotation Item List',
                'description' => 'This permission allows a user to view the list of quotation items',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation_item.show',
                'display_name' => 'Showing Quotation Item Detail',
                'description' => 'This permission allows a user to view the details of a specific quotation item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation_item.create',
                'display_name' => 'Creating Quotation Item',
                'description' => 'This permission allows a user to create a new quotation item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation_item.edit',
                'display_name' => 'Editing Quotation Item',
                'description' => 'This permission allows a user to edit an existing quotation item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'quotation_item.destroy',
                'display_name' => 'Deleting Quotation Item',
                'description' => 'This permission allows a user to delete a quotation item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice.index',
                'display_name' => 'Showing Invoice List',
                'description' => 'This permission allows a user to view the list of invoices',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice.show',
                'display_name' => 'Showing Invoice Detail',
                'description' => 'This permission allows a user to view the details of a specific invoice',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice.create',
                'display_name' => 'Creating Invoice',
                'description' => 'This permission allows a user to create a new invoice',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice.edit',
                'display_name' => 'Editing Invoice',
                'description' => 'This permission allows a user to edit an existing invoice',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice.destroy',
                'display_name' => 'Deleting Invoice',
                'description' => 'This permission allows a user to delete an invoice',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice_item.index',
                'display_name' => 'Showing Invoice Item List',
                'description' => 'This permission allows a user to view the list of invoice items',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice_item.show',
                'display_name' => 'Showing Invoice Item Detail',
                'description' => 'This permission allows a user to view the details of a specific invoice item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice_item.create',
                'display_name' => 'Creating Invoice Item',
                'description' => 'This permission allows a user to create a new invoice item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice_item.edit',
                'display_name' => 'Editing Invoice Item',
                'description' => 'This permission allows a user to edit an existing invoice item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'invoice_item.destroy',
                'display_name' => 'Deleting Invoice Item',
                'description' => 'This permission allows a user to delete an invoice item',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_bank.index',
                'display_name' => 'Showing Company Bank List',
                'description' => 'This permission allows a user to view the list of company banks',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_bank.show',
                'display_name' => 'Showing Company Bank Detail',
                'description' => 'This permission allows a user to view the details of a specific company bank',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_bank.create',
                'display_name' => 'Creating Company Bank',
                'description' => 'This permission allows a user to create a new company bank',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_bank.edit',
                'display_name' => 'Editing Company Bank',
                'description' => 'This permission allows a user to edit an existing company bank',
                'guard_name' => 'web',
            ],
            [
                'name' => 'company_bank.destroy',
                'display_name' => 'Deleting Company Bank',
                'description' => 'This permission allows a user to delete a company bank',
                'guard_name' => 'web',
            ],
            [
                'name' => 'transaction.index',
                'display_name' => 'Showing Transaction List',
                'description' => 'This permission allows a user to view the list of transactions',
                'guard_name' => 'web',
            ],
            [
                'name' => 'transaction.show',
                'display_name' => 'Showing Transaction Detail',
                'description' => 'This permission allows a user to view the details of a specific transaction',
                'guard_name' => 'web',
            ],
            [
                'name' => 'transaction.create',
                'display_name' => 'Creating Transaction',
                'description' => 'This permission allows a user to create a new transaction',
                'guard_name' => 'web',
            ],
            [
                'name' => 'transaction.edit',
                'display_name' => 'Editing Transaction',
                'description' => 'This permission allows a user to edit an existing transaction',
                'guard_name' => 'web',
            ],
            [
                'name' => 'transaction.destroy',
                'display_name' => 'Deleting Transaction',
                'description' => 'This permission allows a user to delete a transaction',
                'guard_name' => 'web',
            ],
            [
                'name' => 'project.index',
                'display_name' => 'Showing Project List',
                'description' => 'This permission allows a user to view the list of projects',
                'guard_name' => 'web',
            ],
            [
                'name' => 'project.show',
                'display_name' => 'Showing Project Detail',
                'description' => 'This permission allows a user to view the details of a specific project',
                'guard_name' => 'web',
            ],
            [
                'name' => 'project.create',
                'display_name' => 'Creating Project',
                'description' => 'This permission allows a user to create a new project',
                'guard_name' => 'web',
            ],
            [
                'name' => 'project.edit',
                'display_name' => 'Editing Project',
                'description' => 'This permission allows a user to edit an existing project',
                'guard_name' => 'web',
            ],
            [
                'name' => 'project.destroy',
                'display_name' => 'Deleting Project',
                'description' => 'This permission allows a user to delete a project',
                'guard_name' => 'web',
            ],

        ];

        Permission::insert($permissions);

        // Grant all permissions to super_admin
        $all_permissions = Permission::all();
        $super_admin_role->syncPermissions($all_permissions);

        // Grant permissions to admin
        $admin_permissions = Permission::whereNotIn('id', [1, 3, 4, 5])->get();
        $admin_role->syncPermissions($admin_permissions);

        // Grant permissions to employee
        $employee_permissions = Permission::whereIn('name', [
            'attendance.index',
            'attendance.show',
            'attendance.create',
            'attendance.edit',
            'attendance.destroy',
            'company.show',
            'company_branch.show',
            'employee.show',
            'salary_view.index',
            'salary_view.show',
            'leave.index',
            'leave.show',
            'leave.create',
            'leave.edit',
            'leave.destroy',
            'claim.index',
            'claim.show',
            'claim.create',
            'claim.edit',
            'claim.destroy',
            'project.index',
            'project.show',
            'project.create',
            'project.edit',
            'project.destroy',
            'bank.index',
            'bank.show',
            'company_bank.index',
            'company_bank.show',
            'company_bank.create',
            'company_bank.edit',
            'company_bank.destroy',
            'transaction.index',
            'transaction.show',
            'transaction.create',
            'transaction.edit',
            'transaction.destroy',
            'invoice.index',
            'invoice.show',
            'invoice.create',
            'invoice.edit',
            'invoice.destroy',
            'invoice_item.index',
            'invoice_item.show',
            'invoice_item.create',
            'invoice_item.edit',
            'invoice_item.destroy',
            'quatation.index',
            'quatation.show',
            'quatation.create',
            'quatation.edit',
            'quatation.destroy',
            'customer_reference.index',
            'customer_reference.show',
            'customer_reference.create',
            'customer_reference.edit',
            'customer_reference.destroy',
            'entity.index',
            'entity.show',
            'entity.create',
            'entity.edit',
            'entity.destroy',
            'entity_address.index',
            'entity_address.show',
            'entity_address.create',
            'entity_address.edit',
            'entity_address.destroy',
            'entity_contact.index',
            'entity_contact.show',
            'entity_contact.create',
            'entity_contact.edit',
            'entity_contact.destroy',
            'product.index',
            'product.show',
            'product.create',
            'product.edit',
            'product.destroy',
            'product_category.index',
            'product_category.show',
            'product_category.create',
            'product_category.edit',
            'product_category.destroy',
        ])->get();
        $employee_role->syncPermissions($employee_permissions);
    }
}
